import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './styles/globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mafia site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <article className="max-w-[1440px] mx-auto min-h-screen">
          {children}
        </article>
      </body>
    </html>
  );
}
