import type { Metadata } from "next";
import localFont from "next/font/local";
import cn from "classnames";
import "./styles/globals.css";

const keetano = localFont({
  src: "../../public/fonts/keetano_katana.ttf",
  display: "swap",
  variable: "--font-keetano",
});
const keetanoKB = localFont({
  src: "../../public/fonts/keetano_katana_killbill.ttf",
  display: "swap",
  variable: "--font-keetanoKB",
});
const obrazec = localFont({
  src: "../../public/fonts/Obrazec-2.ttf",
  display: "swap",
  variable: "--font-obrazec",
});
const relieve = localFont({
  src: "../../public/fonts/Relieve.ttf",
  display: "swap",
  variable: "--font-relieve",
});
const involveSB = localFont({
  src: "../../public/fonts/Involve-SemiBold.ttf",
  display: "swap",
  variable: "--font-involveSB",
});
const involveRG = localFont({
  src: "../../public/fonts/Involve-Regular.ttf",
  display: "swap",
  variable: "--font-involveRG",
});
const involveBQ = localFont({
  src: "../../public/fonts/Involve-Oblique.ttf",
  display: "swap",
  variable: "--font-involveBQ",
});

export const metadata: Metadata = {
  title: "Mafia site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          keetano.className,
          keetanoKB.variable,
          obrazec.variable,
          relieve.variable,
          involveSB.variable,
          involveRG.variable,
          involveBQ.variable,
          "bg-link"
        )}
      >
        {children}
      </body>
    </html>
  );
}
